sudo: required
dist: trusty

language: c

env:
  global:
  - GOSS_VERSION=0.3.5
  - GOSS_PATH=/usr/local/bin/goss
  - secure: "sEpdf2+Qn6hzUn8icz7YvS3M7KjHdLR6XCkb5sE2MugmU377WZ2zSQCPQENDg1Pc6JeMnmcJ1A0s4ygQxg0MF+NgiCOChOds0sSCh/iXhGFE94Bz2hmq0+hRsap+JEc557+ZppeFvCORhfhd1A9TktBDdoVw37l8riNE1b2U/ThhIdYkzI4wYRiQWBIkeEPbx46p11DueZZg49kPTFc9tOCj3n6PPcvQd0tJ8hPXBcJl9YHrGLQZs9BLile8s0V9TgGTTyxA9SJFAtj3kpWnfyJ3JA7b44xGNQUy02/i7hWOeLZABHW/hvvDq/qU6zn7/VVuym2ikL8DCd5RS+j1d9K6bA5kt9TbmfVOQDHdBrvtTZJB6HPGuRfc8JULbbMZEo1WRsfL04Y6+dNfo9I/HWPYstTDCjaWAYb67vjVwvAE3RvVRPZOoYPIqJ9yr/H2/szfOMoBTIwEfDMvQo5DC2XTqz/yhkXFGpnagzmJaMuYWOTzMDZ2lHa+q8O2juxCtXCHOtN5T0uW2fKCH/bIIV+pyWewegGvkNTAvbfQOJU4lteQlFFJCmjDu0x1sR1fAcQ6e57Dx6UTSgu+GADwAyqy0fUHE3EeSbUHmTK6Eqem1D89HbjoLLg/YQlLCVXUJRAIlWWuuVY7PkkD5vNuSGvp+UwuvKj+Vs96AClzfb0="
  - secure: "qeX9TQnHVXVjy4YXXxu0cmNNIdIJBS9EoZ/DDD71ALuM2fV/0vEV1kgOsDyMg+77JZ6YjYUvBiS1pXUM3u0neagVE893myuPzacv1am58xiPfNFUUD56Q0TmnQDjN4QFARPM+f4BoRw72lwE4Zv2vEYPZAum1uI/KYbZ8BgDCZzc6ANFnnDr73jDLxKvnpc65nTgKXi0hi0iWIhg7IZhLA4MJczxuRzPeyAk1rG1hSw8MSapCOkuLbkhaC3Jl38BKMtDTU8pnviRL8xh7tCEUHppuN+NlAqLnV2H4k7/6TdrLUS32rkj+9Tt+UKVopvzBHO0vzmcpnddkvPLZNRvXirhraxBEbCEaOX0MAt9ixHqaIuIuavtLAcxtR+1B7u8NVOS7gryY5Uc2mnGfU1I8u21Cf14d23m6OMz7vf7tXGBfDbrZp1gPKBCUl9y+eCpWkfF2n20IGmzqsFYVmsPx2ikTqPkQ2LsAtOLe7MKw3/n/17P/tmHV6k1EWYu0VYI5udpipkOK22KI90WWnoFXNzVuH21cSQ4b+4fJ1pcusOLvvFATopG27drV5ETpAam5kUsGtKoVoESsqeIh9ZCBzlveqQiQw5Up2n8T47rym2E07vKcCzmZ97JldLXjXd79r1n8dz+KYEfsSzKoRQtLemB10HqZ8Q6nHhkXelDQLM="

services:
  - docker

before_install:
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/goss-linux-amd64 -o /usr/local/bin/goss
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/dgoss -o /usr/local/bin/dgoss
  - sudo chmod +rx /usr/local/bin/goss
  - sudo chmod +rx /usr/local/bin/dgoss

install: true

script:
  - make test
  - make push
