sudo: required
language: c

env:
  - GOSS_VERSION=0.3.5
  - GOSS_PATH=/usr/local/bin/goss

services:
  - docker

before_install:
  curl -L https://github.com/aelsabbahy/goss/releases/download/$GOSS_VERSION/goss-linux-amd64 -o /usr/local/bin/goss
  curl -L https://github.com/aelsabbahy/goss/releases/download/$GOSS_VERSION/dgoss -o /usr/local/bin/dgoss
  chmod +rx /usr/local/bin/goss
  chmod +rx /usr/local/bin/dgoss

jobs:
  - stage: test
    script: make test
  - stage: deploy
    script: make push
