sudo: required
dist: trusty

language: c

env:
  - GOSS_VERSION=0.3.5 GOSS_PATH=/usr/local/bin/goss

services:
  - docker

before_install:
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/goss-linux-amd64 -o /usr/local/bin/goss
  - sudo curl -L https://github.com/aelsabbahy/goss/releases/download/v$GOSS_VERSION/dgoss -o /usr/local/bin/dgoss
  - sudo chmod +rx /usr/local/bin/goss
  - sudo chmod +rx /usr/local/bin/dgoss

install: true

script:
  - make test
  - make push
